---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels: 
    app: nginx-cm
spec:
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
    envFrom:
    - configMapRef:
        name: env-cm

