---
apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-hard
  labels:
    app: node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: diskspeed
            operator: In 
            values:
            - high
            - medium
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
      name: tcp-80