---
apiVersion: v1
kind: Pod
metadata:
  name: node-antiaffinity-soft
  labels:
    app: node-antiaffinity
spec:
  affinity: 
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference: 
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - magnetic
            - low
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
      name: tcp-80