apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: tcp-80    
    nodePort: 32000
    port: 80
    targetPort: 80
    protocol: TCP