
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod 
  labels:
    app: nginx
spec:
  containers:
  - name: webserver
    image: nginx:1.25
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"


