---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: webserver
      image: nginx:latest
      volumeMounts:
      - mountPath: /var/mysql
        name: sc-mysql-vol
      ports:
        - containerPort: 80  

  volumes:
  - name: sc-mysql-vol
    secret:
      secretName: sc-vol      



