
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql 
  labels:
    app: mysql-pv
spec:
  containers:
    - name: database 
      image: mysql:8
      envFrom:
        - secretRef:
            name: sc-env
      volumeMounts:
        - name: from-internal-storage
          mountPath: /var/lib/mysql 
  volumes:
    - name: from-internal-storage
      persistentVolumeClaim:
        claimName: mysql-pvc