---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: muthu-role
  labels:
    namespace: develop
rules:
- apiGroups: ["*"] 
  resources: ["deployments","services","pods","configmaps"]
  verbs: ["get","list","delete","update","create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: muthu-rolebinding
  labels:
    namespace: develop
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: muthu 
  namespace: develop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role  
  name: muthu-role


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deploy
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: order
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: order-pod
      labels:
        app: order
        version: "1.0"
    spec:
      containers:
        - name: order
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: muthu-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["deployments","services","pods","configmaps"]
  verbs: ["get","list","delete","update","create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: muthu-clusterrole-rolebinding
  labels:
    namespace: develop
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: muthu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: muthu-clusterrole       
