apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc-np
  labels:
    app: nginx-node-port
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: 80-tcp
    port: 80
    targetPort: 80
    nodePort: 32000   
    protocol: TCP