---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc-lb
  labels:
    app: nginx-lb
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: 32000-tcp
    port: 32000
    targetPort: 80 
    protocol: TCP

