apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: myapp
spec:
  containers:
    - name: webserver
      image: httpd
      ports:
        - name: web-httpd
          containerPort: 80
          protocol: TCP