---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exp-sts-nginx
spec:
  selector:
    matchLabels:
      app: nginx-pod  
  serviceName: stateful-svc
  replicas: 3 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: webserver
        image: nginx
        ports:
        - containerPort: 80
          name: web-80
        volumeMounts:
        - name: dummy-sts
          mountPath: /dummy
  volumeClaimTemplates:
  - metadata:
      name: dummy-sts
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: managed-premium
      resources:
        requests:
          storage: 5Gi