apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
    purpose: rc-demo
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: webserver
        image: httpd
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
              
