apiVersion: v1
kind: Pod
metadata:
  name: c1
spec:
  containers:
  - name: c1
    image: nginx:1.25
    ports:
    - containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: c2
spec:
  containers:
  - name: c2
    image: nginx:1.25
    ports:
    - containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: c3
spec:
  containers:
  - name: c3
    image: nginx:1.25
    ports:
    - containerPort: 80
      protocol: TCP
---
