---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nodeselector
spec:
  nodeSelector:
    disktype: ssd
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
      name: tcp-80

